### ISSUE TITLE
Problem with  libtorch_cuda_cu.so

### ISSUE THREAD

**Issue by efyphil** [facebookresearch/MCC#11]
I tried to check you demo and use conda pytorch3d env but get this problem 
Traceback (most recent call last):
  File "/home/ubuntu/Philip/MCC/demo.py", line 12, in <module>
    from pytorch3d.io.obj_io import load_obj
  File "/opt/conda/envs/pytorch3d/lib/python3.9/site-packages/pytorch3d/io/__init__.py", line 8, in <module>
    from .obj_io import load_obj, load_objs_as_meshes, save_obj
  File "/opt/conda/envs/pytorch3d/lib/python3.9/site-packages/pytorch3d/io/obj_io.py", line 22, in <module>
    from pytorch3d.renderer import TexturesAtlas, TexturesUV
  File "/opt/conda/envs/pytorch3d/lib/python3.9/site-packages/pytorch3d/renderer/__init__.py", line 7, in <module>
    from .blending import (
  File "/opt/conda/envs/pytorch3d/lib/python3.9/site-packages/pytorch3d/renderer/blending.py", line 10, in <module>
    from pytorch3d import _C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

**Comment by chaoyuaw** [comment]
Hi @efyphil , This seems to be related to PyTorch3D installation issues. I did a quick search on PyTorch3D repo, and found some issues that look similar to yours. For example, https://github.com/facebookresearch/pytorch3d/issues/1246 might be related? Can you try the proposed fixes there?
