### ISSUE TITLE
Uknown subset name : fewview_dev

### ISSUE THREAD

**Issue by aradhyamathur** [facebookresearch/MCC#8]
Hi, I downloaded and tried to load the dataset however encountered the following error with pytorch3d using the prepare_co3d.py script provided.
The data was downloaded using the script provided [here](https://github.com/facebookresearch/co3d/) for single sequence subset using the command `python ./co3d/download_dataset.py --download_folder <DOWNLOAD_FOLDER> --single_sequence_subset` .
The following is the complete stack trace. Any guidance would be highly appreciated.
```
Traceback (most recent call last):
  File "/home/aradhya/mcc/MCC/scripts/prepare_co3d.py", line 46, in <module>
    main(args)
  File "/home/aradhya/mcc/MCC/scripts/prepare_co3d.py", line 27, in main
    dataset_map = get_dataset_map(
  File "/home/aradhya/mcc/MCC/scripts/../util/co3d_utils.py", line 49, in get_dataset_map
    dataset_map_provider = JsonIndexDatasetMapProviderV2(
  File "<string>", line 15, in __init__
  File "/home/aradhya/anaconda3/envs/mccenv/lib/python3.9/site-packages/pytorch3d/implicitron/dataset/json_index_dataset_map_provider_v2.py", line 214, in __post_init__
    dataset_map = self._load_category(self.category)
  File "/home/aradhya/anaconda3/envs/mccenv/lib/python3.9/site-packages/pytorch3d/implicitron/dataset/json_index_dataset_map_provider_v2.py", line 264, in _load_category
    raise ValueError(
ValueError: Unknown subset name fewview_dev. Choose one of available subsets: ['manyview_dev_0', 'manyview_dev_1', 'manyview_test_0'].
```

**Comment by chaoyuaw** [comment]
Hi @aradhyamathur , 

It looks like CO3Dv2 does have "fewview_dev" as described in 
https://github.com/facebookresearch/co3d/#available-subset-names-in-co3dv2

I wonder if it's "--single_sequence_subset" that caused the issue. If the issue still persists, asking support in the CO3D dataset repo might help, too.

Alternatively, if you don't care about using the exactly same train/val split as our implementation, I think changing the subset name to "manyview_dev_0" (or whatever subset you can use without issue) might work too.

**Comment by aradhyamathur** [comment]
Yeah renaming the subset does the trick for now. Will look into it further, maybe "--single_seuquence_subset" causes the issue.

**Comment by aradhyamathur** [comment]
the dataloader also faces some issues due to missing ply files in the same setting
