### ISSUE TITLE
RuntimeError: No shared folder available

### ISSUE THREAD

**Issue by Tangshitao** [facebookresearch/MCC#9]
Traceback (most recent call last):
  File "submitit_mcc.py", line 133, in <module>
    main()
  File "submitit_mcc.py", line 123, in main
    args.dist_url = get_init_file().as_uri()
  File "submitit_mcc.py", line 48, in get_init_file
    os.makedirs(str(get_shared_folder()), exist_ok=True)
  File "submitit_mcc.py", line 43, in get_shared_folder
    raise RuntimeError("No shared folder available")
RuntimeError: No shared folder available

**Comment by chaoyuaw** [comment]
Hi @Tangshitao , 

Can you try changing [these two lines](https://github.com/facebookresearch/MCC/blob/main/submitit_mcc.py#L39-L40) to use a folder that exists and works conveniently for you?

**Comment by Tangshitao** [comment]
Thanks, but I got another error, 'ValueError: relative path can't be expressed as a file URI'
Traceback (most recent call last):
  File "submitit_mcc.py", line 133, in <module>
    main()
  File "submitit_mcc.py", line 123, in main
    args.dist_url = get_init_file().as_uri()
  File "/opt/conda/lib/python3.7/pathlib.py", line 739, in as_uri
    raise ValueError("relative path can't be expressed as a file URI")
ValueError: relative path can't be expressed as a file URI

**Comment by Tangshitao** [comment]
Does the codes only work for slurm? How to run the codes on a server?

**Comment by chaoyuaw** [comment]
Submitit is mainly for multi-node slurm training. If you don't want to use it, simply "python main_mcc.py" would work too!

**Comment by Tangshitao** [comment]
Thanks, it works.
